---

docs_dir: docs
site_dir: site
site_url: !ENV [SITE_URL, 'https://dev-ops.su']
site_name: !ENV [SITE_NAME, 'DevOps']
site_description: DevOps заметки
site_author: WoozyMasta
copyright: dev-ops.su
repo_url: https://github.com/dev-ops-su
edit_uri: /edit/main/docs/
strict: false

nav:
    - Introduction: 'index.md'
 
theme:
  language: ru

plugins:
    - search:
        lang:
          - en
          - ru

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
