name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.21
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
